spring:
  datasource:
    url: jdbc:h2:mem::setting_testdb
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.H2Dialect
      #show-sql: true
      #ddl-auto: create-drop
